#!/bin/zsh

################################
## Wake County Public Schools ##
## Z Shell function library   ##
################################
## Contributor: Andrew Zimmer ##
## Last updated: 08/04/2022   ##
################################
## Purpose: Get random string ##
################################
## Arguments:                 ##
##   None.                    ##
################################
## Output:                    ##
## - A 10-character string.   ##
################################

get-random-string() {
	# Export our customized path
	export PATH="/Library/WCPSS/Apps/bin/:/Library/WCPSS/Apps/sbin/:Library/WCPSS/Scripts/Executables/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec"

	# Set -e/-o errexit to force the script to terminate on any non-zero exit code
	# Set -u/-o nounset to force the script to exit if unset variables are called
	set -o errexit
	set -o nounset

	# Create variable and populate it with ten random alphanumeric digits.
	local random_string="$(dd if=/dev/random bs=8 count=1 2>/dev/null | od -An -tx1 | tr -d ' \t\n' | tr -d '%')"

	# Return the random string we created.
	echo "${random_string}"
}
